version: '3.8'

services:
  at2024progra2converterservice:
    build:
      context: https://github.com/jpsandovaln/AT2024Progra2ConverterService.git#develop
      dockerfile: Dockerfile
    ports:
      - "${CONVERTER_PORT_HOST}:9090"
    environment:
      - FLASK_ENV=development
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}
    depends_on:
      postgres-db:
        condition: service_healthy

  at2024progra2mlservice:
    build:
      context: https://github.com/jpsandovaln/AT2024Progra2MLService.git#develop
      dockerfile: Dockerfile
    ports:
      - "${ML_PORT_HOST}:5000"
    environment:
      - FLASK_ENV=development
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_HOST}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
